import type { RuleTemplate } from '@/types/tradingRule';

// ─── 新手入门模板 ───
export const beginnerTemplates: RuleTemplate[] = [
  {
    id: 'beginner_ma_cross',
    name: '均线金叉买入',
    description: '当短期均线上穿长期均线时买入，是最经典的趋势跟踪信号。',
    category: 'beginner',
    difficulty: 'easy',
    riskLevel: 'low',
    tags: ['趋势', '均线', '新手友好'],
    rule: {
      name: '均线金叉买入',
      description: 'MA5 上穿 MA10 时买入',
      category: '均线系统',
      tags: ['趋势', '均线'],
      enabled: true,
      buyCondition: {
        type: 'composite',
        logic: 'and',
        conditions: [
          { type: 'indicator', indicator: 'ma', field: 'ma5', compare: 'cross_above', refField: 'ma10', params: { period: 5 } },
          { type: 'volume', compare: 'above', value: 1.0, maPeriod: 5 },
        ],
      },
      sellCondition: {
        type: 'composite',
        logic: 'or',
        conditions: [
          { type: 'indicator', indicator: 'ma', field: 'ma5', compare: 'cross_below', refField: 'ma10', params: { period: 5 } },
          { type: 'price', field: 'close', compare: 'below', refIndicator: 'ma', refField: 'ma20' },
        ],
      },
      buyAction: { type: 'buy', label: '金叉买入', color: '#22c55e' },
      sellAction: { type: 'sell', label: '死叉卖出', color: '#ef4444' },
      stopLoss: { enabled: true, type: 'fixed', value: 8 },
      takeProfit: { enabled: true, type: 'fixed', value: 15 },
      timeframe: 'day',
    },
  },
  {
    id: 'beginner_volume_breakout',
    name: '放量突破买入',
    description: '当成交量放大且价格突破近期高点时买入，捕捉突破行情。',
    category: '量价关系',
    difficulty: 'easy',
    riskLevel: 'low',
    tags: ['突破', '量价', '新手友好'],
    rule: {
      name: '放量突破买入',
      description: '成交量 > MA5×1.5 且价格创20日新高',
      category: '量价关系',
      tags: ['突破', '量价'],
      enabled: true,
      buyCondition: {
        type: 'composite',
        logic: 'and',
        conditions: [
          { type: 'volume', compare: 'above', value: 1.5, maPeriod: 5 },
          { type: 'price', field: 'close', compare: 'above', value: 0 },  // 将由引擎计算 HHV
        ],
      },
      sellCondition: {
        type: 'composite',
        logic: 'or',
        conditions: [
          { type: 'price', field: 'close', compare: 'below', refIndicator: 'ma', refField: 'ma10' },
          { type: 'volume', compare: 'below', value: 0.5, maPeriod: 5 },
        ],
      },
      buyAction: { type: 'buy', label: '放量突破', color: '#22c55e' },
      sellAction: { type: 'sell', label: '缩量回落', color: '#ef4444' },
      stopLoss: { enabled: true, type: 'fixed', value: 8 },
      takeProfit: { enabled: true, type: 'fixed', value: 15 },
      timeframe: 'day',
    },
  },
];

// ─── 趋势跟踪模板 ───
export const trendTemplates: RuleTemplate[] = [
  {
    id: 'trend_macd_golden',
    name: 'MACD 金叉趋势',
    description: 'MACD 金叉确认趋势启动，结合均线过滤假信号。',
    category: 'MACD',
    difficulty: 'medium',
    riskLevel: 'medium',
    tags: ['趋势', 'MACD', '动量'],
    rule: {
      name: 'MACD 金叉趋势',
      description: 'DIF 上穿 DEA 且 MA20 向上',
      category: 'MACD',
      tags: ['趋势', 'MACD'],
      enabled: true,
      buyCondition: {
        type: 'composite',
        logic: 'and',
        conditions: [
          { type: 'indicator', indicator: 'macd', field: 'dif', compare: 'cross_above', refField: 'dea' },
          { type: 'price', field: 'close', compare: 'above', refIndicator: 'ma', refField: 'ma20' },
        ],
      },
      sellCondition: {
        type: 'composite',
        logic: 'or',
        conditions: [
          { type: 'indicator', indicator: 'macd', field: 'dif', compare: 'cross_below', refField: 'dea' },
          { type: 'price', field: 'close', compare: 'below', refIndicator: 'ma', refField: 'ma20' },
        ],
      },
      buyAction: { type: 'buy', label: 'MACD金叉', color: '#22c55e' },
      sellAction: { type: 'sell', label: 'MACD死叉', color: '#ef4444' },
      stopLoss: { enabled: true, type: 'trailing', value: 5 },
      takeProfit: { enabled: true, type: 'fixed', value: 25 },
      timeframe: 'day',
    },
  },
  {
    id: 'trend_dmi_adx',
    name: 'DMI 趋势确认',
    description: 'DMI 金叉 + ADX > 25 确认趋势强度，避免盘整期假信号。',
    category: 'DMI',
    difficulty: 'medium',
    riskLevel: 'medium',
    tags: ['趋势', 'DMI', 'ADX'],
    rule: {
      name: 'DMI 趋势确认',
      description: '+DI 上穿 -DI 且 ADX > 25',
      category: 'DMI',
      tags: ['趋势', 'DMI'],
      enabled: true,
      buyCondition: {
        type: 'composite',
        logic: 'and',
        conditions: [
          { type: 'indicator', indicator: 'dmi', field: 'pdi', compare: 'cross_above', refField: 'mdi' },
          { type: 'indicator', indicator: 'dmi', field: 'adx', compare: 'above', value: 25 },
        ],
      },
      sellCondition: {
        type: 'composite',
        logic: 'or',
        conditions: [
          { type: 'indicator', indicator: 'dmi', field: 'mdi', compare: 'cross_above', refField: 'pdi' },
          { type: 'indicator', indicator: 'dmi', field: 'adx', compare: 'below', value: 20 },
        ],
      },
      buyAction: { type: 'buy', label: 'DMI金叉', color: '#22c55e' },
      sellAction: { type: 'sell', label: 'DMI死叉', color: '#ef4444' },
      stopLoss: { enabled: true, type: 'trailing', value: 5 },
      takeProfit: { enabled: true, type: 'fixed', value: 25 },
      timeframe: 'day',
    },
  },
  {
    id: 'trend_sar_follow',
    name: 'SAR 追踪止损',
    description: 'SAR 抛物线转向，适合追踪趋势，自动移动止损位。',
    category: 'SAR',
    difficulty: 'medium',
    riskLevel: 'medium',
    tags: ['趋势', 'SAR', '止损'],
    rule: {
      name: 'SAR 追踪止损',
      description: '价格上穿 SAR 买入，下穿卖出',
      category: 'SAR',
      tags: ['趋势', 'SAR'],
      enabled: true,
      buyCondition: {
        type: 'indicator',
        indicator: 'sar',
        field: 'close',
        compare: 'cross_above',
        refField: 'sar',
      },
      sellCondition: {
        type: 'indicator',
        indicator: 'sar',
        field: 'close',
        compare: 'cross_below',
        refField: 'sar',
      },
      buyAction: { type: 'buy', label: 'SAR翻多', color: '#22c55e' },
      sellAction: { type: 'sell', label: 'SAR翻空', color: '#ef4444' },
      stopLoss: { enabled: false, type: 'fixed', value: 0 },
      takeProfit: { enabled: false, type: 'fixed', value: 0 },
      timeframe: 'day',
    },
  },
];

// ─── 短线交易模板 ───
export const shorttermTemplates: RuleTemplate[] = [
  {
    id: 'short_kdj_rsi',
    name: 'KDJ+RSI 超卖反弹',
    description: 'KDJ 和 RSI 同时超卖时买入，短线反弹策略。',
    category: 'KDJ',
    difficulty: 'medium',
    riskLevel: 'high',
    tags: ['短线', 'KDJ', 'RSI', '超卖'],
    rule: {
      name: 'KDJ+RSI 超卖反弹',
      description: 'KDJ<20 且 RSI<30 时买入',
      category: 'KDJ',
      tags: ['短线', '超卖'],
      enabled: true,
      buyCondition: {
        type: 'composite',
        logic: 'and',
        conditions: [
          { type: 'indicator', indicator: 'kdj', field: 'k', compare: 'below', value: 20 },
          { type: 'indicator', indicator: 'rsi', field: 'rsi', compare: 'below', value: 30 },
        ],
      },
      sellCondition: {
        type: 'composite',
        logic: 'or',
        conditions: [
          { type: 'indicator', indicator: 'kdj', field: 'k', compare: 'above', value: 80 },
          { type: 'indicator', indicator: 'rsi', field: 'rsi', compare: 'above', value: 70 },
        ],
      },
      buyAction: { type: 'buy', label: '超卖反弹', color: '#22c55e' },
      sellAction: { type: 'sell', label: '超买回落', color: '#ef4444' },
      stopLoss: { enabled: true, type: 'fixed', value: 5 },
      takeProfit: { enabled: true, type: 'fixed', value: 8 },
      timeframe: 'day',
    },
  },
  {
    id: 'short_wr_reversal',
    name: 'WR 威廉反转',
    description: '威廉指标 WR 超卖区反弹，短线快速交易。',
    category: 'WR',
    difficulty: 'medium',
    riskLevel: 'high',
    tags: ['短线', 'WR', '反转'],
    rule: {
      name: 'WR 威廉反转',
      description: 'WR 从超卖区(>80)向下穿越时买入',
      category: 'WR',
      tags: ['短线', '反转'],
      enabled: true,
      buyCondition: {
        type: 'indicator',
        indicator: 'wr',
        field: 'wr10',
        compare: 'cross_below',
        value: 80,
      },
      sellCondition: {
        type: 'indicator',
        indicator: 'wr',
        field: 'wr10',
        compare: 'cross_above',
        value: 20,
      },
      buyAction: { type: 'buy', label: 'WR超卖反弹', color: '#22c55e' },
      sellAction: { type: 'sell', label: 'WR超买回落', color: '#ef4444' },
      stopLoss: { enabled: true, type: 'fixed', value: 5 },
      takeProfit: { enabled: true, type: 'fixed', value: 8 },
      timeframe: 'day',
    },
  },
  {
    id: 'short_atr_breakout',
    name: 'ATR 波动突破',
    description: '当 ATR 收缩后放大且价格突破时入场，捕捉波动率扩张。',
    category: 'ATR',
    difficulty: 'hard',
    riskLevel: 'high',
    tags: ['短线', 'ATR', '突破', '波动率'],
    rule: {
      name: 'ATR 波动突破',
      description: 'ATR 从低位放大 + 价格突破20日高点',
      category: 'ATR',
      tags: ['短线', '突破'],
      enabled: true,
      buyCondition: {
        type: 'composite',
        logic: 'and',
        conditions: [
          { type: 'indicator', indicator: 'atr', field: 'atr', compare: 'above', value: 0 },
          { type: 'price', field: 'close', compare: 'above', value: 0 },
        ],
      },
      sellCondition: {
        type: 'price',
        field: 'close',
        compare: 'below',
        refIndicator: 'atr',
        refField: 'stop',
      },
      buyAction: { type: 'buy', label: '波动突破', color: '#22c55e' },
      sellAction: { type: 'sell', label: 'ATR止损', color: '#ef4444' },
      stopLoss: { enabled: true, type: 'atr', value: 2.5 },
      takeProfit: { enabled: true, type: 'fixed', value: 10 },
      timeframe: 'day',
    },
  },
];

// ─── 价值投资模板 ───
export const valueTemplates: RuleTemplate[] = [
  {
    id: 'value_boll_oversold',
    name: '布林带超卖买入',
    description: '价格触及布林带下轨时买入，均值回归策略。',
    category: '布林带',
    difficulty: 'easy',
    riskLevel: 'medium',
    tags: ['价值', '布林带', '均值回归'],
    rule: {
      name: '布林带超卖买入',
      description: '价格跌破布林带下轨时买入',
      category: '布林带',
      tags: ['价值', '均值回归'],
      enabled: true,
      buyCondition: {
        type: 'price',
        field: 'close',
        compare: 'below',
        refIndicator: 'boll',
        refField: 'lower',
      },
      sellCondition: {
        type: 'price',
        field: 'close',
        compare: 'above',
        refIndicator: 'boll',
        refField: 'upper',
      },
      buyAction: { type: 'buy', label: '触及下轨', color: '#22c55e' },
      sellAction: { type: 'sell', label: '触及上轨', color: '#ef4444' },
      stopLoss: { enabled: true, type: 'fixed', value: 15 },
      takeProfit: { enabled: true, type: 'fixed', value: 50 },
      timeframe: 'week',
    },
  },
  {
    id: 'value_ma_long',
    name: '长期均线价值',
    description: '价格在长期均线附近企稳时买入，适合长线投资。',
    category: '均线',
    difficulty: 'easy',
    riskLevel: 'medium',
    tags: ['价值', '均线', '长线'],
    rule: {
      name: '长期均线价值',
      description: '价格在 MA60 附近企稳 + 成交量萎缩',
      category: '均线',
      tags: ['价值', '长线'],
      enabled: true,
      buyCondition: {
        type: 'composite',
        logic: 'and',
        conditions: [
          { type: 'price', field: 'close', compare: 'above', refIndicator: 'ma', refField: 'ma60' },
          { type: 'volume', compare: 'below', value: 0.8, maPeriod: 20 },
        ],
      },
      sellCondition: {
        type: 'price',
        field: 'close',
        compare: 'below',
        refIndicator: 'ma',
        refField: 'ma60',
      },
      buyAction: { type: 'buy', label: '均线企稳', color: '#22c55e' },
      sellAction: { type: 'sell', label: '跌破均线', color: '#ef4444' },
      stopLoss: { enabled: true, type: 'fixed', value: 15 },
      takeProfit: { enabled: true, type: 'fixed', value: 50 },
      timeframe: 'week',
    },
  },
];

// ─── 导出所有模板 ───
export const ALL_TEMPLATES: RuleTemplate[] = [
  ...beginnerTemplates,
  ...trendTemplates,
  ...shorttermTemplates,
  ...valueTemplates,
];

export const TEMPLATE_CATEGORIES = [
  { id: 'beginner', label: '新手入门', icon: '🌱', description: '简单易懂，风险较低' },
  { id: 'trend', label: '趋势跟踪', icon: '📈', description: '中线为主，跟随趋势' },
  { id: 'shortterm', label: '短线交易', icon: '⚡', description: '快速进出，高风险高收益' },
  { id: 'value', label: '价值投资', icon: '💎', description: '长线持有，均值回归' },
] as const;
