// ─── 通达信内置公式模板库 ───

export interface TdxTemplate {
  id: string;
  name: string;
  category: string;
  code: string;
  description: string;
}

export const TDX_TEMPLATES: TdxTemplate[] = [
  // ── 趋势类 ──
  {
    id: 'ma_cross',
    name: '均线金叉/死叉',
    category: '趋势',
    code: [
      'MA5:=MA(CLOSE,5);',
      'MA10:=MA(CLOSE,10);',
      'MA20:=MA(CLOSE,20);',
      'MA5线:MA5,COLORWHITE;',
      'MA10线:MA10,COLORYELLOW;',
      'MA20线:MA20,COLORYELLOW;',
      '金叉:CROSS(MA5,MA10),COLORRED;',
      '死叉:CROSS(MA10,MA5),COLORGREEN;',
    ].join('\n'),
    description: 'MA5 上穿 MA10 金叉买入，下穿死叉卖出',
  },
  {
    id: 'macd_custom',
    name: '自定义 MACD',
    category: '趋势',
    code: [
      'DIF:EMA(CLOSE,12)-EMA(CLOSE,26),COLORWHITE;',
      'DEA:EMA(DIF,9),COLORYELLOW;',
      'MACD:(DIF-DEA)*2,COLORRED;',
      '零轴:0,COLORGRAY;',
      'STICKLINE(MACD>0,MACD,0),COLORRED;',
      'STICKLINE(MACD<0,MACD,0),COLORGREEN;',
    ].join('\n'),
    description: '经典 MACD 指标，DIF/DEA 金叉看多，红绿柱切换',
  },
  {
    id: 'boll_custom',
    name: '自定义布林带',
    category: '趋势',
    code: [
      'MID:MA(CLOSE,20),COLORWHITE;',
      'UPPER:MID+2*STD(CLOSE,20),COLORRED;',
      'LOWER:MID-2*STD(CLOSE,20),COLORGREEN;',
      '上轨:UPPER,COLORRED;',
      '下轨:LOWER,COLORGREEN;',
      '中轨:MID,COLORYELLOW;',
    ].join('\n'),
    description: '布林带上中下轨，价格触及上轨超买，触及下轨超卖',
  },
  {
    id: 'sar_custom',
    name: 'SAR 抛物线',
    category: '趋势',
    code: [
      'N:=BARSLAST(CLOSE>REF(CLOSE,1));',
      '趋势:IF(CLOSE>REF(CLOSE,1),1,-1),COLORRED;',
      'STICKLINE(CLOSE>REF(CLOSE,1),CLOSE,OPEN),COLORRED;',
      'STICKLINE(CLOSE<=REF(CLOSE,1),CLOSE,OPEN),COLORGREEN;',
    ].join('\n'),
    description: '简化版 SAR，红涨绿跌',
  },

  // ── 振荡类 ──
  {
    id: 'rsi_custom',
    name: '自定义 RSI',
    category: '振荡',
    code: [
      'RSI6:RSI(CLOSE,6),COLORWHITE;',
      'RSI12:RSI(CLOSE,12),COLORYELLOW;',
      'RSI24:RSI(CLOSE,24),COLORYELLOW;',
      '超买:80,COLORRED;',
      '超卖:20,COLORGREEN;',
      '强弱:50,COLORGRAY;',
    ].join('\n'),
    description: 'RSI 6/12/24 三线，>80 超买，<20 超卖',
  },
  {
    id: 'kdj_custom',
    name: '自定义 KDJ',
    category: '振荡',
    code: [
      'RSV:=(CLOSE-LLV(LOW,9))/(HHV(HIGH,9)-LLV(LOW,9))*100;',
      'K:=SMA(RSV,3,1),COLORWHITE;',
      'D:=SMA(K,3,1),COLORYELLOW;',
      'J:=3*K-2*D,COLORYELLOW;',
      '超买:80,COLORRED;',
      '超卖:20,COLORGREEN;',
    ].join('\n'),
    description: 'KDJ 随机指标，J 值极值预示拐点',
  },
  {
    id: 'cci_custom',
    name: '自定义 CCI',
    category: '振荡',
    code: [
      'TP:=(HIGH+LOW+CLOSE)/3;',
      'CCI:(TP-MA(TP,14))/(0.015*AVEDEV(TP,14)),COLORWHITE;',
      '超买:100,COLORRED;',
      '超卖:-100,COLORGREEN;',
      '零轴:0,COLORGRAY;',
    ].join('\n'),
    description: '顺势指标 CCI，±100 穿越确认趋势',
  },
  {
    id: 'wr_custom',
    name: '威廉指标 WR',
    category: '振荡',
    code: [
      'WR10:(HHV(HIGH,10)-CLOSE)/(HHV(HIGH,10)-LLV(LOW,10))*100,COLORWHITE;',
      'WR6:(HHV(HIGH,6)-CLOSE)/(HHV(HIGH,6)-LLV(LOW,6))*100,COLORYELLOW;',
      '超买:20,COLORRED;',
      '超卖:80,COLORGREEN;',
    ].join('\n'),
    description: '威廉指标，<20 超买，>80 超卖',
  },

  // ── 量能类 ──
  {
    id: 'vol_ma',
    name: '成交量均线',
    category: '量能',
    code: [
      'VOLMA5:MA(VOL,5),COLORWHITE;',
      'VOLMA10:MA(VOL,10),COLORYELLOW;',
      'VOLMA20:MA(VOL,20),COLORYELLOW;',
      '放量:IF(VOL>MA(VOL,20)*2,1,0),COLORRED;',
    ].join('\n'),
    description: '成交量均线，放量突破辅助判断',
  },
  {
    id: 'obv_custom',
    name: 'OBV 能量潮',
    category: '量能',
    code: [
      'OBV线:OBV,COLORWHITE;',
      'OBVMA:MA(OBV,20),COLORYELLOW;',
    ].join('\n'),
    description: 'OBV 量价同步验证',
  },

  // ── 综合类 ──
  {
    id: 'power_line',
    name: '动力线 0~100',
    category: '综合',
    code: [
      'LLV20:=LLV(LOW,20);',
      'HHV20:=HHV(HIGH,20);',
      '动力:EMA((CLOSE-LLV20)/(HHV20-LLV20)*100,4),COLORWHITE;',
      '清仓:90,COLORRED;',
      '阶段:80,COLORYELLOW;',
      '强弱:50,COLORGRAY;',
      '关注:30,COLORYELLOW;',
      '底部:15,COLORGREEN;',
    ].join('\n'),
    description: '通达信经典动力线，0~100 区间判断',
  },
  {
    id: 'multi_ma',
    name: '多头排列',
    category: '综合',
    code: [
      'MA5:MA(CLOSE,5),COLORWHITE;',
      'MA10:MA(CLOSE,10),COLORYELLOW;',
      'MA20:MA(CLOSE,20),COLORYELLOW;',
      'MA60:MA(CLOSE,60),COLORYELLOW;',
      'MA120:MA(CLOSE,120),COLORYELLOW;',
      '多头:IF(MA5>MA10 AND MA10>MA20 AND MA20>MA60,1,0),COLORRED;',
    ].join('\n'),
    description: '多头排列检测，短期均线在长期均线上方',
  },
  {
    id: 'atr_stop',
    name: 'ATR 止损',
    category: '综合',
    code: [
      'TR:=MAX(MAX(HIGH-LOW,ABS(HIGH-REF(CLOSE,1))),ABS(LOW-REF(CLOSE,1)));',
      'ATR14:MA(TR,14),COLORWHITE;',
      '上轨:CLOSE+2.5*ATR14,COLORRED;',
      '下轨:CLOSE-2.5*ATR14,COLORGREEN;',
      '止损:CLOSE-2.5*ATR14,COLORYELLOW;',
    ].join('\n'),
    description: '基于 ATR 的动态止损位',
  },
  {
    id: 'divergence',
    name: '底背离检测',
    category: '综合',
    code: [
      'RSI14:RSI(CLOSE,14),COLORWHITE;',
      '价格低点:IF(CLOSE<REF(CLOSE,1) AND REF(CLOSE,1)<REF(CLOSE,2),1,0),COLORGREEN;',
      'RSI低点:IF(RSI14<REF(RSI14,1) AND REF(RSI14,1)<REF(RSI14,2),1,0),COLORYELLOW;',
      '底背离:IF(CLOSE<REF(CLOSE,5) AND RSI14>REF(RSI14,5),1,0),COLORRED;',
    ].join('\n'),
    description: '价格创新低但 RSI 未创新低，底背离信号',
  },
  // ── 趋势类（新增） ──
  {
    id: 'ema_cross',
    name: 'EMA 金叉死叉',
    category: '趋势',
    code: [
      'EMA12:EMA(CLOSE,12),COLORWHITE;',
      'EMA26:EMA(CLOSE,26),COLORYELLOW;',
      '金叉:CROSS(EMA12,EMA26),COLORRED;',
      '死叉:CROSS(EMA26,EMA12),COLORGREEN;',
    ].join('\n'),
    description: 'EMA12 上穿 EMA26 金叉买入，下穿死叉卖出',
  },
  {
    id: 'triple_ma_align',
    name: '三均线多头排列',
    category: '趋势',
    code: [
      'MA5:=MA(CLOSE,5);',
      'MA10:=MA(CLOSE,10);',
      'MA20:=MA(CLOSE,20);',
      'MA5线:MA5,COLORWHITE;',
      'MA10线:MA10,COLORYELLOW;',
      'MA20线:MA20,COLORCYAN;',
      '多头排列:IF(MA5>MA10 AND MA10>MA20,1,0),COLORRED;',
      '空头排列:IF(MA5<MA10 AND MA10<MA20,1,0),COLORGREEN;',
    ].join('\n'),
    description: 'MA5>MA10>MA20 多头排列买入，空头排列卖出',
  },
  {
    id: 'ma_support_resist',
    name: '均线支撑压力',
    category: '趋势',
    code: [
      'MA20:MA(CLOSE,20),COLORWHITE;',
      'MA60:MA(CLOSE,60),COLORYELLOW;',
      '站上20日:IF(CLOSE>MA20 AND REF(CLOSE,1)<=REF(MA20,1),1,0),COLORRED;',
      '跌破20日:IF(CLOSE<MA20 AND REF(CLOSE,1)>=REF(MA20,1),1,0),COLORGREEN;',
      '站上60日:IF(CLOSE>MA60 AND REF(CLOSE,1)<=REF(MA60,1),1,0),COLORYELLOW;',
    ].join('\n'),
    description: '价格突破/跌破 20 日和 60 日均线信号',
  },
  {
    id: 'boll_squeeze',
    name: '布林收口突破',
    category: '趋势',
    code: [
      'MID:MA(CLOSE,20),COLORWHITE;',
      'UPPER:MID+2*STD(CLOSE,20),COLORYELLOW;',
      'LOWER:MID-2*STD(CLOSE,20),COLORYELLOW;',
      '带宽:(UPPER-LOWER)/MID*100,COLORCYAN;',
      '收口:IF(REF(带宽,1)>带宽 AND 带宽<REF(带宽,5),1,0),COLORRED;',
      '突破上轨:IF(CLOSE>UPPER AND REF(CLOSE,1)<=REF(UPPER,1),1,0),COLORMAGENTA;',
    ].join('\n'),
    description: '布林带收口后价格突破上轨的买入信号',
  },
  {
    id: 'price_channel',
    name: '唐奇安通道',
    category: '趋势',
    code: [
      'UPPER:HHV(HIGH,20),COLORWHITE;',
      'LOWER:LLV(LOW,20),COLORYELLOW;',
      'MID:(UPPER+LOWER)/2,COLORCYAN;',
      '突破上轨:IF(CLOSE>REF(UPPER,1),1,0),COLORRED;',
      '跌破下轨:IF(CLOSE<REF(LOWER,1),1,0),COLORGREEN;',
    ].join('\n'),
    description: '唐奇安通道突破系统，20 日高低点通道',
  },
  // ── 振荡类（新增） ──
  {
    id: 'stochastic_custom',
    name: 'KDJ 随机指标',
    category: '振荡',
    code: [
      'RSV:=(CLOSE-LLV(LOW,9))/(HHV(HIGH,9)-LLV(LOW,9))*100;',
      'K:SMA(RSV,3,1),COLORWHITE;',
      'D:SMA(K,3,1),COLORYELLOW;',
      'J:3*K-2*D,COLORCYAN;',
      '超买:IF(J>100,1,0),COLORRED;',
      '超卖:IF(J<0,1,0),COLORGREEN;',
    ].join('\n'),
    description: 'KDJ 随机指标，J 值超买超卖信号',
  },
  {
    id: 'trix_indicator',
    name: 'TRIX 三重指数',
    category: '振荡',
    code: [
      'TR:=EMA(EMA(EMA(CLOSE,12),12),12);',
      'TRIX:(TR-REF(TR,1))/REF(TR,1)*100,COLORWHITE;',
      'MATRIX:EMA(TRIX,9),COLORYELLOW;',
      '金叉:CROSS(TRIX,MATRIX),COLORRED;',
      '死叉:CROSS(MATRIX,TRIX),COLORGREEN;',
    ].join('\n'),
    description: 'TRIX 三重指数平滑移动平均线金叉死叉',
  },
  {
    id: 'bias_bias',
    name: 'BIAS 乖离率',
    category: '振荡',
    code: [
      'BIAS6:(CLOSE-MA(CLOSE,6))/MA(CLOSE,6)*100,COLORWHITE;',
      'BIAS12:(CLOSE-MA(CLOSE,12))/MA(CLOSE,12)*100,COLORYELLOW;',
      'BIAS24:(CLOSE-MA(CLOSE,24))/MA(CLOSE,24)*100,COLORCYAN;',
      '超买:IF(BIAS6>5,1,0),COLORRED;',
      '超卖:IF(BIAS6<-5,1,0),COLORGREEN;',
    ].join('\n'),
    description: 'BIAS 乖离率，偏离均线过大时回归',
  },
  {
    id: 'psy_line',
    name: 'PSY 心理线',
    category: '振荡',
    code: [
      'PSY12:COUNT(CLOSE>REF(CLOSE,1),12)/12*100,COLORWHITE;',
      'PSY6:COUNT(CLOSE>REF(CLOSE,1),6)/6*100,COLORYELLOW;',
      '超买:IF(PSY12>75,1,0),COLORRED;',
      '超卖:IF(PSY12<25,1,0),COLORGREEN;',
    ].join('\n'),
    description: 'PSY 心理线，衡量多空力量对比',
  },
  {
    id: 'dpo_indicator',
    name: 'DPO 去趋势价格',
    category: '振荡',
    code: [
      'DPO:CLOSE-MA(CLOSE,20)+MA(CLOSE,10),COLORWHITE;',
      'MADPO:MA(DPO,6),COLORYELLOW;',
      '金叉:CROSS(DPO,MADPO),COLORRED;',
      '死叉:CROSS(MADPO,DPO),COLORGREEN;',
    ].join('\n'),
    description: 'DPO 去趋势价格震荡指标',
  },
  // ── 量能类（新增） ──
  {
    id: 'mfi_indicator',
    name: 'MFI 资金流量',
    category: '量能',
    code: [
      'MFI14:100-100/(1+SUM(IF(MF>REF(MF,1),MF,0),14)/SUM(IF(MF<REF(MF,1),MF,0),14)),COLORWHITE;',
      'MF:=((HIGH+LOW+CLOSE)/3-REF((HIGH+LOW+CLOSE)/3,1))*VOL;',
      '超买:IF(MFI14>80,1,0),COLORRED;',
      '超卖:IF(MFI14<20,1,0),COLORGREEN;',
    ].join('\n'),
    description: 'MFI 资金流量指标，量价结合的 RSI',
  },
  {
    id: 'vwap_line',
    name: 'VWAP 成交均价',
    category: '量能',
    code: [
      'VWAP:SUM(AMOUNT,0)/SUM(VOL,0),COLORWHITE;',
      '价格:CLOSE,COLORYELLOW;',
      '高于均价:IF(CLOSE>VWAP,1,0),COLORRED;',
      '低于均价:IF(CLOSE<VWAP,1,0),COLORGREEN;',
    ].join('\n'),
    description: 'VWAP 成交量加权平均价格',
  },
  {
    id: 'volume_rate',
    name: '量比指标',
    category: '量能',
    code: [
      '量比:VOL/REF(MA(VOL,5),1),COLORWHITE;',
      '放量:IF(量比>2,1,0),COLORRED;',
      '缩量:IF(量比<0.5,1,0),COLORGREEN;',
      '均量线:MA(VOL,5)/REF(MA(VOL,5),1),COLORYELLOW;',
    ].join('\n'),
    description: '量比指标，衡量当日成交量相对平均水平',
  },
  {
    id: 'obv_trend',
    name: 'OBV 能量潮趋势',
    category: '量能',
    code: [
      'OBV1:OBV,COLORWHITE;',
      'MAOBV:MA(OBV,30),COLORYELLOW;',
      '量价齐升:IF(CLOSE>REF(CLOSE,1) AND OBV>REF(OBV,1),1,0),COLORRED;',
      '量价背离:IF(CLOSE>REF(CLOSE,1) AND OBV<REF(OBV,1),1,0),COLORGREEN;',
    ].join('\n'),
    description: 'OBV 能量潮与均线交叉，量价背离检测',
  },
  {
    id: 'volume_price_div',
    name: '量价背离检测',
    category: '量能',
    code: [
      '价格趋势:IF(CLOSE>REF(CLOSE,5),1,IF(CLOSE<REF(CLOSE,5),-1,0)),COLORWHITE;',
      '量能趋势:IF(VOL>REF(MA(VOL,5),1),1,IF(VOL<REF(MA(VOL,5),1),-1,0)),COLORYELLOW;',
      '顶背离:IF(价格趋势=1 AND 量能趋势=-1,1,0),COLORRED;',
      '底背离:IF(价格趋势=-1 AND 量能趋势=1,1,0),COLORGREEN;',
    ].join('\n'),
    description: '价格与成交量趋势背离检测',
  },
  // ── 综合类（新增） ──
  {
    id: 'macd_rsi_combo',
    name: 'MACD+RSI 组合',
    category: '综合',
    code: [
      'DIF:EMA(CLOSE,12)-EMA(CLOSE,26),COLORWHITE;',
      'DEA:EMA(DIF,9),COLORYELLOW;',
      'MACD:(DIF-DEA)*2,COLORCYAN;',
      'RSI14:RSI(CLOSE,14),COLORMAGENTA;',
      'MACD金叉+RSI超卖:IF(CROSS(DIF,DEA) AND RSI14<30,1,0),COLORRED;',
      'MACD死叉+RSI超买:IF(CROSS(DEA,DIF) AND RSI14>70,1,0),COLORGREEN;',
    ].join('\n'),
    description: 'MACD 金叉配合 RSI 超卖的复合买入信号',
  },
  {
    id: 'kdj_ma_combo',
    name: 'KDJ+均线 组合',
    category: '综合',
    code: [
      'RSV:=(CLOSE-LLV(LOW,9))/(HHV(HIGH,9)-LLV(LOW,9))*100;',
      'K:SMA(RSV,3,1),COLORWHITE;',
      'D:SMA(K,3,1),COLORYELLOW;',
      'MA20:MA(CLOSE,20),COLORCYAN;',
      'KDJ金叉+站上均线:IF(CROSS(K,D) AND CLOSE>MA20,1,0),COLORRED;',
      'KDJ死叉+跌破均线:IF(CROSS(D,K) AND CLOSE<MA20,1,0),COLORGREEN;',
    ].join('\n'),
    description: 'KDJ 金叉配合价格站上 20 日均线的买入信号',
  },
  {
    id: 'breakout_system',
    name: '突破交易系统',
    category: '综合',
    code: [
      'N:=20;',
      '上轨:HHV(HIGH,N),COLORWHITE;',
      '下轨:LLV(LOW,N),COLORYELLOW;',
      '中轨:MA(CLOSE,N),COLORCYAN;',
      '突破买入:IF(CLOSE>REF(上轨,1) AND REF(CLOSE,1)<=REF(上轨,1),1,0),COLORRED;',
      '跌破卖出:IF(CLOSE<REF(下轨,1) AND REF(CLOSE,1)>=REF(下轨,1),1,0),COLORGREEN;',
      '止损:中轨,COLORMAGENTA;',
    ].join('\n'),
    description: '20 日高低点突破系统，中轨止损',
  },
  {
    id: 'trend_follow',
    name: '趋势跟踪系统',
    category: '综合',
    code: [
      'EMA12:EMA(CLOSE,12),COLORWHITE;',
      'EMA26:EMA(CLOSE,26),COLORYELLOW;',
      'ATR14:ATR(HIGH,LOW,CLOSE,14),COLORCYAN;',
      '趋势多头:IF(EMA12>EMA26 AND CLOSE>EMA12,1,0),COLORRED;',
      '趋势空头:IF(EMA12<EMA26 AND CLOSE<EMA12,1,0),COLORGREEN;',
      '止损位:CLOSE-2*ATR14,COLORMAGENTA;',
    ].join('\n'),
    description: 'EMA 趋势判断 + ATR 动态止损',
  },
  {
    id: 'reversal_system',
    name: '反转交易系统',
    category: '综合',
    code: [
      'RSI14:RSI(CLOSE,14),COLORWHITE;',
      'MA20:MA(CLOSE,20),COLORYELLOW;',
      'MFI14:100-100/(1+SUM(IF(MF>REF(MF,1),MF,0),14)/SUM(IF(MF<REF(MF,1),MF,0),14)),COLORCYAN;',
      'MF:=((HIGH+LOW+CLOSE)/3-REF((HIGH+LOW+CLOSE)/3,1))*VOL;',
      '底部反转:IF(RSI14<30 AND CLOSE<MA20 AND MFI14<20,1,0),COLORRED;',
      '顶部反转:IF(RSI14>70 AND CLOSE>MA20 AND MFI14>80,1,0),COLORGREEN;',
    ].join('\n'),
    description: 'RSI+均线+MFI 三重确认的反转信号',
  },
];

export const TDX_CATEGORIES = ['趋势', '振荡', '量能', '综合'];
